function equation = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EQUATION = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  EQUATION = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  equation = importfile("/Users/ali.kishk/Desktop/ISB/COVID19/equation.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Mar-2020 16:01:32

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "";

% Specify column names and types
opts.VariableNames = "ala_DASH_L_c0330796arg_DASH_L_c0473996asn_DASH_L_c0350589asp_DA";
opts.VariableTypes = "string";
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
equation = readtable(filename, opts);

end